import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { apiFetch } from '@/lib/api'

export default async function ExecutionDetailPage({ params }: { params: Promise<{ executionId: string }> }) {
  const { executionId }=await params; const supabase=await createClient(); const { data: claims }=await supabase.auth.getClaims(); if(!claims?.claims?.sub) redirect('/login')
  const execution=await apiFetch(`/v1/executions/${executionId}`); if(execution.status===404) notFound(); if(!execution.ok) return <main className="dashboard-shell"><section className="main"><div className="notice error">Unable to load execution.</div></section></main>
  const e=execution.data; const artifacts=await apiFetch(`/v1/executions/${executionId}/artifacts`); const items=Array.isArray(artifacts.data)?artifacts.data:[]
  const result=e.result??{}; const passed=result.passed ?? result.tests_passed ?? result.pass_count; const failed=result.failed ?? result.tests_failed ?? result.fail_count
  return <main className="dashboard-shell"><aside className="sidebar"><Link className="brand" href="/dashboard"><span className="brand-mark">AI</span> AI Testing</Link><nav className="side-links"><Link className="side-link" href="/dashboard">◈ Overview</Link><Link className="side-link" href="/dashboard/projects">▦ Projects</Link><Link className="side-link" href="/dashboard/suites">◇ Test suites</Link><Link className="side-link active" href="/dashboard/executions">↗ Executions</Link><Link className="side-link" href="/dashboard/settings">⚙ Settings</Link></nav></aside><section className="main"><div className="topline page-header"><div><div className="breadcrumb"><Link href="/dashboard/executions">Executions</Link> <span>/</span> {executionId.slice(0,12)}</div><h1>Execution {executionId.slice(0,12)}</h1><p className="page-subtitle">{e.base_url||'No base URL'} · {e.browser} · {e.workers} worker{e.workers===1?'':'s'}</p></div><span className={`execution-status ${e.status}`}>{e.status}</span></div><div className="stats"><div className="card stat"><span className="muted">Status</span><strong>{e.status}</strong></div><div className="card stat"><span className="muted">Passed</span><strong>{passed??'—'}</strong></div><div className="card stat"><span className="muted">Failed</span><strong>{failed??'—'}</strong></div><div className="card stat"><span className="muted">Artifacts</span><strong>{items.length}</strong></div></div><div className="result-layout"><div className="card"><div className="section-heading"><div><div className="panel-kicker">RESULT</div><h2>Run details</h2></div></div><dl className="detail-list"><div><dt>Suite</dt><dd>{e.metadata?.suite_filename??e.suite_path}</dd></div><div><dt>Suite version</dt><dd>v{e.metadata?.suite_version??'—'}</dd></div><div><dt>Created</dt><dd>{e.created_at?new Date(e.created_at).toLocaleString():'—'}</dd></div><div><dt>Started</dt><dd>{e.started_at?new Date(e.started_at).toLocaleString():'—'}</dd></div><div><dt>Finished</dt><dd>{e.finished_at?new Date(e.finished_at).toLocaleString():'—'}</dd></div></dl>{e.error&&<div className="notice error">{e.error}</div>}<pre className="result-json">{JSON.stringify(e.result??{message:'Results will appear here when the worker completes the run.'},null,2)}</pre></div><div className="card"><div className="section-heading"><div><div className="panel-kicker">ARTIFACTS</div><h2>Run files</h2></div></div><div className="artifact-list">{items.map((a:any)=><div className="artifact-row" key={a.id}><div className="artifact-icon">▤</div><div><strong>{a.name}</strong><small>{a.content_type} · {Math.ceil(a.size_bytes/1024)} KB</small></div><Link className="btn" href={`/dashboard/executions/${executionId}/artifacts/${a.id}`}>Open</Link></div>)}{!items.length&&<div className="mini-empty"><div>▤</div><strong>No artifacts yet</strong><span>HTML, JSON and other runner outputs will be listed here.</span></div>}</div></div></div></section></main>
}
