import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export default async function SuiteDetailPage({ params }: { params: Promise<{ suiteId:string }> }) {
  const {suiteId}=await params; const supabase=await createClient(); const {data:claims}=await supabase.auth.getClaims(); if(!claims?.claims?.sub) redirect('/login')
  const {data:suite}=await supabase.from('test_suites').select('id,name,slug,project_id,created_at').eq('id',suiteId).single(); if(!suite) notFound()
  const {data:project}=await supabase.from('projects').select('id,name').eq('id',suite.project_id).single()
  const {data:versions}=await supabase.from('test_suite_versions').select('id,version,filename,content_type,size_bytes,sha256,created_at,storage_path').eq('test_suite_id',suiteId).order('version',{ascending:false})
  return <main className="dashboard-shell"><aside className="sidebar"><Link className="brand" href="/dashboard"><span className="brand-mark">AI</span> AI Testing</Link><nav className="side-links"><Link className="side-link" href="/dashboard">◈ Overview</Link><Link className="side-link" href="/dashboard/projects">▦ Projects</Link><Link className="side-link active" href="/dashboard/suites">◇ Test suites</Link><Link className="side-link" href="/dashboard/executions">↗ Executions</Link><Link className="side-link" href="/dashboard/settings">⚙ Settings</Link></nav></aside><section className="main"><div className="topline page-header"><div><div className="breadcrumb"><Link href="/dashboard/suites">Test suites</Link> <span>/</span> {suite.name}</div><h1>{suite.name}</h1><p className="page-subtitle">{project?.name??'Project'} · {versions?.length??0} immutable versions</p></div><Link className="btn btn-primary" href={`/dashboard/executions?project=${suite.project_id}&suite=${suite.id}`}>Run latest →</Link></div><div className="card" style={{marginTop:24}}><div className="section-heading"><div><div className="panel-kicker">VERSION HISTORY</div><h2>Immutable versions</h2></div></div><div className="version-list">{(versions??[]).map((v:any)=><div className="version-row" key={v.id}><div className="version-badge">v{v.version}</div><div><strong>{v.filename}</strong><small>{v.content_type} · {Math.ceil(v.size_bytes/1024)} KB · {new Date(v.created_at).toLocaleString()}</small><code>{v.sha256}</code></div><span className="muted">Stored privately</span></div>)}{!versions?.length&&<div className="mini-empty"><strong>No versions</strong></div>}</div></div></section></main>
}
