import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { apiFetch } from '@/lib/api'
import { createApiKey, revokeApiKey } from '../settings/actions'

export default async function ApiKeysPage() {
  const supabase=await createClient(); const {data:claims}=await supabase.auth.getClaims(); if(!claims?.claims?.sub) redirect('/login')
  const {data:orgs}=await supabase.from('organizations').select('id,name').order('created_at').limit(1); const org=orgs?.[0]
  const {data:projects}=org?await supabase.from('projects').select('id,name').eq('organization_id',org.id).order('created_at'):{data:[]}; const project=projects?.[0]
  const response=project?await apiFetch(`/v1/projects/${project.id}/api-keys`):{ok:false,data:[] as any[]}; const keys=Array.isArray(response.data)?response.data:[]
  return <main className="dashboard-shell"><aside className="sidebar"><Link className="brand" href="/dashboard"><span className="brand-mark">AI</span> AI Testing</Link><nav className="side-links"><Link className="side-link" href="/dashboard">◈ Overview</Link><Link className="side-link" href="/dashboard/projects">▦ Projects</Link><Link className="side-link" href="/dashboard/suites">◇ Test suites</Link><Link className="side-link" href="/dashboard/executions">↗ Executions</Link><Link className="side-link" active-color="true" href="/dashboard/api-keys">⌁ API keys</Link><Link className="side-link" href="/dashboard/settings">⚙ Settings</Link></nav></aside><section className="main"><div className="topline page-header"><div><div className="breadcrumb">Workspace <span>/</span> API keys</div><h1>API keys</h1><p className="page-subtitle">Project-scoped credentials for CI/CD, CLI and automated test runs.</p></div><Link className="btn" href="/dashboard/settings">Settings</Link></div><div className="card" style={{marginTop:24}}><div className="panel-kicker">PROJECT ACCESS</div><h2>{project?.name??'No project'}</h2>{project?<><form action={createApiKey} className="inline-form"><input type="hidden" name="project_id" value={project.id}/><input name="name" placeholder="GitHub Actions" required maxLength={120}/><button className="btn btn-primary">Create API key</button></form><div className="key-list">{keys.map((key:any)=><div className="key-row" key={key.id}><div><strong>{key.name}</strong><small>{key.key_prefix} · {key.revoked_at?'Revoked':'Active'}</small></div>{!key.revoked_at&&<form action={revokeApiKey}><input type="hidden" name="project_id" value={project.id}/><input type="hidden" name="key_id" value={key.id}/><button className="btn">Revoke</button></form>}</div>)}{!keys.length&&<div className="mini-empty"><div>⌁</div><strong>No keys yet</strong><span>Create a key when you are ready to connect CI/CD.</span></div>}</div></>:<div className="mini-empty"><strong>Create a project first</strong><Link className="btn btn-primary" href="/dashboard/projects">Create project</Link></div>}</div></section></main>
}
