import Link from 'next/link'
import { notFound, redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import SignOutButton from '../../sign-out-button'

export default async function ProjectPage({ params }: { params: Promise<{ projectId: string }> }) {
  const supabase = await createClient()
  const { data: claims } = await supabase.auth.getClaims()
  if (!claims?.claims) redirect('/login')
  const { projectId } = await params
  const { data: project } = await supabase.from('projects').select('id,name,slug,organization_id,created_at').eq('id', projectId).single()
  if (!project) notFound()
  const { data: suites } = await supabase.from('test_suites').select('id,name,slug,updated_at').eq('project_id', project.id).order('updated_at', { ascending: false }).limit(6)
  const { data: executions } = await supabase.from('executions').select('id,status,base_url,browser,created_at,finished_at').eq('project_id', project.id).order('created_at', { ascending: false }).limit(6)

  return <main className="dashboard-shell"><aside className="sidebar"><Link className="brand" href="/dashboard"><span className="brand-mark">AI</span><span>AI Testing</span></Link><div className="workspace-switcher"><span className="workspace-dot"/><div><small>Project</small><strong>{project.name}</strong></div></div><nav className="side-links"><Link className="side-link" href="/dashboard"><span>⌂</span>Overview</Link><Link className="side-link active" href="/dashboard/projects"><span>◈</span>Projects</Link><Link className="side-link" href="/dashboard/suites"><span>◇</span>Test suites</Link><Link className="side-link" href="/dashboard/executions"><span>◌</span>Executions</Link><Link className="side-link" href="/dashboard/settings"><span>⚙</span>Settings</Link></nav><div className="sidebar-bottom"><SignOutButton /></div></aside><section className="main"><header className="topline page-header"><div><div className="breadcrumb"><Link href="/dashboard/projects">Projects</Link><span>/</span>{project.name}</div><h1>{project.name}</h1><p className="page-subtitle">{project.slug} · Ready for test suites and cloud executions.</p></div><div className="header-actions"><Link className="btn btn-ghost" href="/dashboard/projects">Back</Link><Link className="btn btn-primary" href="/dashboard/suites">＋ Upload suite</Link></div></header><div className="stats"><div className="card"><span className="muted">Test suites</span><strong>{suites?.length || 0}</strong></div><div className="card"><span className="muted">Recent executions</span><strong>{executions?.length || 0}</strong></div><div className="card"><span className="muted">Status</span><strong style={{fontSize:20}}>Ready</strong></div><div className="card"><span className="muted">Browser</span><strong style={{fontSize:20}}>Chromium</strong></div></div><section className="section" style={{paddingTop:30}}><div className="project-grid"><article className="card"><h3>Test suites</h3><p>Versioned test definitions associated with this project.</p>{suites?.length ? suites.map(s => <div key={s.id} className="project-open" style={{marginTop:10,border:0,padding:'10px 0'}}><strong>{s.name}</strong><span>{s.slug}</span></div>) : <p>No suites yet. Upload your first suite to start testing.</p>}</article><article className="card"><h3>Recent executions</h3><p>Latest cloud test runs for this application.</p>{executions?.length ? executions.map(e => <div key={e.id} className="project-open" style={{marginTop:10,border:0,padding:'10px 0'}}><strong>{e.status}</strong><span>{e.browser}</span></div>) : <p>No executions yet. Your first run will appear here.</p>}</article></div></section></section></main>
}
